address django.http.request.RawPostDataException
accessing request.body seems to be causing this exception:
django.http.request.RawPostDataException: You cannot access body after
reading from request's data stream
This may be b/c the middleware is already accessing the data stream,
see https://stackoverflow.com/questions/19581110